### ISSUE TITLE
Errors on emtpy station set

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pdp_util#6]
I'm seeing a number of the following error in the pdp error logs.

```python
[2016-11-14 11:48:06 +0000] [4063] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/gunicorn/workers/async.py", line 112, in handle_request
    for item in respiter:
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/pdp-2.3.6-py2.7.egg/pdp/error.py", line 62, in __call__
    start_response(status, response_headers, sys.exc_info())
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 241, in start_response
    reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/pdp-2.3.6-py2.7.egg/pdp/error.py", line 56, in __call__
    for block in response_iter:
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/ga_wsgi_client/__init__.py", line 41, in __call__
    for chunk in app_iter:
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/pdp_util/agg.py", line 79, in ziperator
    for name, responder in responders:
  File "/home/websites/tools.pacificclimate.org/data_portal-2.3.6/pdp/pyenv/local/lib/python2.7/site-packages/pdp_util/agg.py", line 97, in get_all_metadata_index_responders
    nets = set(zip(*stations)[0])
IndexError: list index out of range
```

It looks like it's probably receiving an empty set of stations. [Corresponding request](https://tools.pacificclimate.org/dataportal/data/pcds/agg/?from-date=1950%2F01%2F01&to-date=2000%2F12%2F01&input-polygon=&input-var=air_temperature_mean&network-name=EC&input-freq=&data-format=xlsx&download-climatology=Climatology).

**Comment by jameshiebert** [comment]
Duplicate of #8
